//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResultDetail
    {
        public int ID { get; set; }
        public Nullable<int> IDMatchResult { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> GoalType { get; set; }
        public Nullable<int> GoalTime { get; set; }
    }
}
